# Generated by Django 5.0.2 on 2024-04-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categories_alter_pproducts_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
    ]
