# Generated by Django 5.0.2 on 2024-04-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_categories_options_alter_categories_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
