# Generated by Django 5.0.2 on 2024-06-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_categories_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='pproducts',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='login',
            field=models.CharField(max_length=25, null=True, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.TextField(null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='pproducts',
            name='category',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pproducts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pproducts',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
