# Generated by Django 5.0.2 on 2024-06-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_categories_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='login',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
