# Generated by Django 5.0.2 on 2024-06-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_model_user'),
        ('catalog', '0008_remove_person_login_remove_person_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
