# Generated by Django 5.0.2 on 2024-06-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_model',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='cart_model',
            name='user',
            field=models.CharField(max_length=120, null=True, verbose_name='Пользователь'),
        ),
    ]
