# Generated by Django 5.0.2 on 2024-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_model_add_date_alter_cart_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_model',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
