# Generated by Django 5.0.2 on 2024-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_model_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=60, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес доставки')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('paid_choice', models.BooleanField(default=False, verbose_name='Оплата при получении')),
                ('delivery_choice', models.BooleanField(default=False, verbose_name='Требуется доставка')),
                ('status', models.CharField(default='В обработке', max_length=30)),
                ('user', models.CharField(max_length=50, null=True, verbose_name='Пользователь')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Цена товара')),
                ('product', models.CharField(max_length=120, null=True, verbose_name='Товар')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
