# Generated by Django 5.0.2 on 2024-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_model',
            name='delivery_choice',
            field=models.TextField(default=False, verbose_name='Требуется доставка'),
        ),
        migrations.AlterField(
            model_name='order_model',
            name='paid_choice',
            field=models.TextField(default=False, verbose_name='Оплата при получении'),
        ),
    ]
