# Generated by Django 5.0.2 on 2024-06-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_products_model_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_products_model',
            name='user',
        ),
        migrations.AddField(
            model_name='order_model',
            name='user',
            field=models.CharField(max_length=50, null=True, verbose_name='Пользователь'),
        ),
    ]
