# Generated by Django 5.0.2 on 2024-06-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_model_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='person1',
        ),
    ]
