# Generated by Django 5.0.2 on 2024-06-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_jans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jans',
        ),
    ]
