# Generated by Django 5.0.2 on 2024-06-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_model_user'),
        ('user', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person1',
        ),
    ]
