# Generated by Django 5.0.2 on 2024-06-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_person1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person1',
        ),
    ]
