# Generated by Django 5.0.2 on 2024-06-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_person1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
