# Generated by Django 5.0.2 on 2024-06-20 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_person_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
